/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGConnectJNI {
  public final static native void XPGWifiBinding_szMac_set(long jarg1, XPGWifiBinding jarg1_, String jarg2);
  public final static native String XPGWifiBinding_szMac_get(long jarg1, XPGWifiBinding jarg1_);
  public final static native void XPGWifiBinding_szDid_set(long jarg1, XPGWifiBinding jarg1_, String jarg2);
  public final static native String XPGWifiBinding_szDid_get(long jarg1, XPGWifiBinding jarg1_);
  public final static native void XPGWifiBinding_szPasscode_set(long jarg1, XPGWifiBinding jarg1_, String jarg2);
  public final static native String XPGWifiBinding_szPasscode_get(long jarg1, XPGWifiBinding jarg1_);
  public final static native long new_XPGWifiBinding();
  public final static native void delete_XPGWifiBinding(long jarg1);
  public final static native void XPGWifiSDKListener_onGetSSIDList(long jarg1, XPGWifiSDKListener jarg1_, long jarg2, XPGWifiSSIDList jarg2_, int jarg3);
  public final static native void XPGWifiSDKListener_onSetAirLink(long jarg1, XPGWifiSDKListener jarg1_, long jarg2, XPGWifiDevice jarg2_);
  public final static native void XPGWifiSDKListener_onDiscovered(long jarg1, XPGWifiSDKListener jarg1_, int jarg2, long jarg3, XPGWifiDeviceList jarg3_);
  public final static native void XPGWifiSDKListener_onRegisterUser(long jarg1, XPGWifiSDKListener jarg1_, int jarg2);
  public final static native void XPGWifiSDKListener_onPrepareBindListFromLocal(long jarg1, XPGWifiSDKListener jarg1_, int jarg2);
  public final static native void XPGWifiSDKListener_onUpdatedBindListFromServer(long jarg1, XPGWifiSDKListener jarg1_, int jarg2);
  public final static native long XPGWifiSDKListener_onCalculateCRC(long jarg1, XPGWifiSDKListener jarg1_, byte[] jarg2);
  public final static native void XPGWifiSDKListener_onUpdateProduct(long jarg1, XPGWifiSDKListener jarg1_, int jarg2);
  public final static native long new_XPGWifiSDKListener();
  public final static native void delete_XPGWifiSDKListener(long jarg1);
  public final static native void XPGWifiSDKListener_director_connect(XPGWifiSDKListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void XPGWifiSDKListener_change_ownership(XPGWifiSDKListener obj, long cptr, boolean take_or_release);
  public final static native void XPGWifiDeviceListener_onConnected(long jarg1, XPGWifiDeviceListener jarg1_);
  public final static native void XPGWifiDeviceListener_onConnectFailed(long jarg1, XPGWifiDeviceListener jarg1_);
  public final static native void XPGWifiDeviceListener_onDisconnected(long jarg1, XPGWifiDeviceListener jarg1_);
  public final static native void XPGWifiDeviceListener_onGetPasscode(long jarg1, XPGWifiDeviceListener jarg1_, int jarg2);
  public final static native void XPGWifiDeviceListener_onLogin(long jarg1, XPGWifiDeviceListener jarg1_, int jarg2);
  public final static native void XPGWifiDeviceListener_onLoginMQTT(long jarg1, XPGWifiDeviceListener jarg1_, int jarg2);
  public final static native boolean XPGWifiDeviceListener_onReceiveData(long jarg1, XPGWifiDeviceListener jarg1_, String jarg2);
  public final static native void XPGWifiDeviceListener_onUnbindFromServices(long jarg1, XPGWifiDeviceListener jarg1_, int jarg2);
  public final static native void XPGWifiDeviceListener_onDeviceOnline(long jarg1, XPGWifiDeviceListener jarg1_, boolean jarg2);
  public final static native void XPGWifiDeviceListener_onSetSwitcher(long jarg1, XPGWifiDeviceListener jarg1_, int jarg2);
  public final static native void XPGWifiDeviceListener_onDeviceLog(long jarg1, XPGWifiDeviceListener jarg1_, short jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long new_XPGWifiDeviceListener();
  public final static native void delete_XPGWifiDeviceListener(long jarg1);
  public final static native void XPGWifiDeviceListener_director_connect(XPGWifiDeviceListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void XPGWifiDeviceListener_change_ownership(XPGWifiDeviceListener obj, long cptr, boolean take_or_release);
  public final static native void XPGWifiSSID_ssid_set(long jarg1, XPGWifiSSID jarg1_, String jarg2);
  public final static native String XPGWifiSSID_ssid_get(long jarg1, XPGWifiSSID jarg1_);
  public final static native void XPGWifiSSID_rssi_set(long jarg1, XPGWifiSSID jarg1_, short jarg2);
  public final static native short XPGWifiSSID_rssi_get(long jarg1, XPGWifiSSID jarg1_);
  public final static native long new_XPGWifiSSID();
  public final static native void delete_XPGWifiSSID(long jarg1);
  public final static native long XPGWifiSSIDList_GetCount(long jarg1, XPGWifiSSIDList jarg1_);
  public final static native long XPGWifiSSIDList_GetItem(long jarg1, XPGWifiSSIDList jarg1_, int jarg2);
  public final static native long new_XPGWifiSSIDList();
  public final static native void delete_XPGWifiSSIDList(long jarg1);
  public final static native long XPGWifiDeviceList_GetCount(long jarg1, XPGWifiDeviceList jarg1_);
  public final static native long XPGWifiDeviceList_GetItem(long jarg1, XPGWifiDeviceList jarg1_, int jarg2);
  public final static native void delete_XPGWifiDeviceList(long jarg1);
  public final static native long new_XPGWifiDeviceList();
  public final static native long XPGWifiBindingList_GetCount(long jarg1, XPGWifiBindingList jarg1_);
  public final static native long XPGWifiBindingList_GetItem(long jarg1, XPGWifiBindingList jarg1_, int jarg2);
  public final static native long new_XPGWifiBindingList();
  public final static native void delete_XPGWifiBindingList(long jarg1);
  public final static native int XPGWifiLogLevelError_get();
  public final static native int XPGWifiError_NONE_get();
  public final static native int XPGWifiError_GENERAL_get();
  public final static native int XPGWifiError_NOT_IMPLEMENTED_get();
  public final static native int XPGWifiError_DESCRIPTOR_FAIL_get();
  public final static native int XPGWifiError_PACKET_DATALEN_get();
  public final static native int XPGWifiError_CONNECTION_ID_get();
  public final static native int XPGWifiError_PATH_get();
  public final static native int XPGWifiError_CONNECTION_CLOSED_get();
  public final static native int XPGWifiError_PACKET_CHECKSUM_get();
  public final static native int XPGWifiError_LOGIN_FAIL_get();
  public final static native int XPGWifiError_DOMAIN_NAME_get();
  public final static native int XPGWifiError_MQTT_FAIL_get();
  public final static native int XPGWifiError_DISCOVERY_MISMATCH_get();
  public final static native int XPGWifiError_SET_SOCK_OPT_get();
  public final static native int XPGWifiError_THREAD_CREATE_get();
  public final static native int XPGWifiError_NULL_MAC_get();
  public final static native int XPGWifiError_CONNECTION_POOL_FULLED_get();
  public final static native int XPGWifiError_NULL_CLIENT_ID_get();
  public final static native int XPGWifiError_CONNECTION_ERROR_get();
  public final static native int XPGWifiError_INVALID_PARAM_get();
  public final static native int XPGWifiError_CONNECT_TIMEOUT_get();
  public final static native int XPGWifiError_INVALID_VERSION_get();
  public final static native int XPGWifiError_INSUFFIENT_MEM_get();
  public final static native int XPGWifiError_THREAD_BUSY_get();
  public final static native int XPGWifiLoginError_CONTROL_ENABLED_get();
  public final static native void XPGWifiSDK_listener_set(long jarg1, XPGWifiSDK jarg1_, long jarg2, XPGWifiSDKListener jarg2_);
  public final static native long XPGWifiSDK_listener_get(long jarg1, XPGWifiSDK jarg1_);
  public final static native long XPGWifiSDK_sharedInstance();
  public final static native void XPGWifiSDK_SetLogLevel(int jarg1);
  public final static native void XPGWifiSDK_SetLogFile(String jarg1);
  public final static native void XPGWifiSDK_SetPrintDataLevel(boolean jarg1);
  public final static native boolean XPGWifiSDK_SetSSID(long jarg1, XPGWifiSDK jarg1_, String jarg2, String jarg3);
  public final static native void XPGWifiSDK_GetSSIDList(long jarg1, XPGWifiSDK jarg1_);
  public final static native boolean XPGWifiSDK_SetAirLink(long jarg1, XPGWifiSDK jarg1_, String jarg2, String jarg3);
  public final static native boolean XPGWifiSDK_DiscoverDevices(long jarg1, XPGWifiSDK jarg1_);
  public final static native void XPGWifiSDK_PrepareBindListFromLocal(long jarg1, XPGWifiSDK jarg1_, String jarg2);
  public final static native void XPGWifiSDK_ClearPreparedBindList(long jarg1, XPGWifiSDK jarg1_);
  public final static native void XPGWifiSDK_UpdateLocalBindListFromServer(long jarg1, XPGWifiSDK jarg1_, String jarg2, String jarg3, float jarg4);
  public final static native void XPGWifiSDK_RegisterUserFromServer(long jarg1, XPGWifiSDK jarg1_, String jarg2, String jarg3);
  public final static native void XPGWifiDevice_listener_set(long jarg1, XPGWifiDevice jarg1_, long jarg2, XPGWifiDeviceListener jarg2_);
  public final static native long XPGWifiDevice_listener_get(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsValidDevice(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsEqualToDevice(long jarg1, XPGWifiDevice jarg1_, long jarg2, XPGWifiDevice jarg2_);
  public final static native String XPGWifiDevice_GetMacAddress(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_GetDid(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_GetPasscode(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_GetIPAddress(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_GetProductKey(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_GetProductName(long jarg1, XPGWifiDevice jarg1_);
  public final static native int XPGWifiDevice_GetConnID(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsConnected(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsLAN(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsOnline(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_IsControl(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_GetPasscodeFromDevice(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_ConnectToLAN(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_ConnectToMQTT(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_Connect(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_Disconnect(long jarg1, XPGWifiDevice jarg1_);
  public final static native void XPGWifiDevice_Login(long jarg1, XPGWifiDevice jarg1_, String jarg2, String jarg3);
  public final static native boolean XPGWifiDevice_IsBind(long jarg1, XPGWifiDevice jarg1_, String jarg2);
  public final static native boolean XPGWifiDevice_Bind(long jarg1, XPGWifiDevice jarg1_, String jarg2);
  public final static native boolean XPGWifiDevice_UnBind(long jarg1, XPGWifiDevice jarg1_, String jarg2);
  public final static native void XPGWifiDevice_UnBindFromService(long jarg1, XPGWifiDevice jarg1_, String jarg2, String jarg3);
  public final static native int XPGWifiDevice_write_bytes(long jarg1, XPGWifiDevice jarg1_, byte[] jarg2);
  public final static native int XPGWifiDevice_write(long jarg1, XPGWifiDevice jarg1_, String jarg2);
  public final static native String XPGWifiDevice_GetUI(long jarg1, XPGWifiDevice jarg1_);
  public final static native String XPGWifiDevice_ForceUpdateUI(long jarg1, XPGWifiDevice jarg1_);
  public final static native boolean XPGWifiDevice_SetSwitcher(long jarg1, XPGWifiDevice jarg1_, boolean jarg2);
  public final static native long new_XPGWifiConfig();
  public final static native long XPGWifiConfig_sharedInstance();
  public final static native boolean XPGWifiConfig_SetProductPath(long jarg1, XPGWifiConfig jarg1_, String jarg2);
  public final static native boolean XPGWifiConfig_AddProduct(long jarg1, XPGWifiConfig jarg1_, String jarg2, String jarg3);
  public final static native void XPGWifiConfig_DownloadProduct(long jarg1, XPGWifiConfig jarg1_, String jarg2);
  public final static native void XPGWifiConfig_SetDebug(long jarg1, XPGWifiConfig jarg1_, boolean jarg2);
  public final static native void XPGWifiConfig_SetSwitchService(long jarg1, XPGWifiConfig jarg1_, boolean jarg2);
  public final static native void XPGWifiConfig_EnableProductFilter(long jarg1, XPGWifiConfig jarg1_, boolean jarg2);
  public final static native void XPGWifiConfig_RegisterProductKey(long jarg1, XPGWifiConfig jarg1_, String jarg2);
  public final static native void XPGWifiConfig_RegisterSSID(long jarg1, XPGWifiConfig jarg1_, String jarg2);
  public final static native void XPGWifiConfig_ClearProductKeys(long jarg1, XPGWifiConfig jarg1_);
  public final static native void XPGWifiConfig_ClearSSIDs(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetTCPPort(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetUDPPort(long jarg1, XPGWifiConfig jarg1_);
  public final static native String XPGWifiConfig_GetMQTTCommunication(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetMQTTCommunicationPort(long jarg1, XPGWifiConfig jarg1_);
  public final static native String XPGWifiConfig_GetMQTTUpdate(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetMQTTUpdatePort(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetAirlinkPort(long jarg1, XPGWifiConfig jarg1_);
  public final static native int XPGWifiConfig_GetSoftAPCount(long jarg1, XPGWifiConfig jarg1_);
  public final static native String XPGWifiConfig_GetSoftAPSSID(long jarg1, XPGWifiConfig jarg1_, int jarg2);
  public final static native void delete_XPGWifiConfig(long jarg1);
  public final static native boolean XPGWifiDatabase_SetStorePath(String jarg1);
  public final static native void XPGWifiDatabase_ClearAll();
  public final static native long new_XPGWifiDatabase();
  public final static native void delete_XPGWifiDatabase(long jarg1);

    static {
        try {
            java.lang.System.loadLibrary("XPGConnect");
        } catch (UnsatisfiedLinkError e) {
            java.lang.System.err.println("JNI error: " + e);
            java.lang.System.exit(1);
        }
    }


  public static void SwigDirector_XPGWifiSDKListener_onGetSSIDList(XPGWifiSDKListener self, long list, int result) {
    self.onGetSSIDList((list == 0) ? null : new XPGWifiSSIDList(list, false), result);
  }
  public static void SwigDirector_XPGWifiSDKListener_onSetAirLink(XPGWifiSDKListener self, long device) {
    self.onSetAirLink((device == 0) ? null : new XPGWifiDevice(device, false));
  }
  public static void SwigDirector_XPGWifiSDKListener_onDiscovered(XPGWifiSDKListener self, int result, long devices) {
    self.onDiscovered(result, (devices == 0) ? null : new XPGWifiDeviceList(devices, false));
  }
  public static void SwigDirector_XPGWifiSDKListener_onRegisterUser(XPGWifiSDKListener self, int result) {
    self.onRegisterUser(result);
  }
  public static void SwigDirector_XPGWifiSDKListener_onPrepareBindListFromLocal(XPGWifiSDKListener self, int result) {
    self.onPrepareBindListFromLocal(result);
  }
  public static void SwigDirector_XPGWifiSDKListener_onUpdatedBindListFromServer(XPGWifiSDKListener self, int result) {
    self.onUpdatedBindListFromServer(result);
  }
  public static long SwigDirector_XPGWifiSDKListener_onCalculateCRC(XPGWifiSDKListener self, byte[] data) {
    return self.onCalculateCRC(data);
  }
  public static void SwigDirector_XPGWifiSDKListener_onUpdateProduct(XPGWifiSDKListener self, int result) {
    self.onUpdateProduct(result);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onConnected(XPGWifiDeviceListener self) {
    self.onConnected();
  }
  public static void SwigDirector_XPGWifiDeviceListener_onConnectFailed(XPGWifiDeviceListener self) {
    self.onConnectFailed();
  }
  public static void SwigDirector_XPGWifiDeviceListener_onDisconnected(XPGWifiDeviceListener self) {
    self.onDisconnected();
  }
  public static void SwigDirector_XPGWifiDeviceListener_onGetPasscode(XPGWifiDeviceListener self, int result) {
    self.onGetPasscode(result);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onLogin(XPGWifiDeviceListener self, int result) {
    self.onLogin(result);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onLoginMQTT(XPGWifiDeviceListener self, int result) {
    self.onLoginMQTT(result);
  }
  public static boolean SwigDirector_XPGWifiDeviceListener_onReceiveData(XPGWifiDeviceListener self, String data) {
    return self.onReceiveData(data);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onUnbindFromServices(XPGWifiDeviceListener self, int result) {
    self.onUnbindFromServices(result);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onDeviceOnline(XPGWifiDeviceListener self, boolean isOnline) {
    self.onDeviceOnline(isOnline);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onSetSwitcher(XPGWifiDeviceListener self, int result) {
    self.onSetSwitcher(result);
  }
  public static void SwigDirector_XPGWifiDeviceListener_onDeviceLog(XPGWifiDeviceListener self, short nLevel, String tag, String source, String content) {
    self.onDeviceLog(nLevel, tag, source, content);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
