/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiDevice {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setListener(XPGWifiDeviceListener value) {
    XPGConnectJNI.XPGWifiDevice_listener_set(swigCPtr, this, XPGWifiDeviceListener.getCPtr(value), value);
  }

  public XPGWifiDeviceListener getListener() {
    long cPtr = XPGConnectJNI.XPGWifiDevice_listener_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XPGWifiDeviceListener(cPtr, false);
  }

  public boolean IsValidDevice() {
    return XPGConnectJNI.XPGWifiDevice_IsValidDevice(swigCPtr, this);
  }

  public boolean IsEqualToDevice(XPGWifiDevice device) {
    return XPGConnectJNI.XPGWifiDevice_IsEqualToDevice(swigCPtr, this, XPGWifiDevice.getCPtr(device), device);
  }

  public String GetMacAddress() {
    return XPGConnectJNI.XPGWifiDevice_GetMacAddress(swigCPtr, this);
  }

  public String GetDid() {
    return XPGConnectJNI.XPGWifiDevice_GetDid(swigCPtr, this);
  }

  public String GetPasscode() {
    return XPGConnectJNI.XPGWifiDevice_GetPasscode(swigCPtr, this);
  }

  public String GetIPAddress() {
    return XPGConnectJNI.XPGWifiDevice_GetIPAddress(swigCPtr, this);
  }

  public String GetProductKey() {
    return XPGConnectJNI.XPGWifiDevice_GetProductKey(swigCPtr, this);
  }

  public String GetProductName() {
    return XPGConnectJNI.XPGWifiDevice_GetProductName(swigCPtr, this);
  }

  public int GetConnID() {
    return XPGConnectJNI.XPGWifiDevice_GetConnID(swigCPtr, this);
  }

  public boolean IsConnected() {
    return XPGConnectJNI.XPGWifiDevice_IsConnected(swigCPtr, this);
  }

  public boolean IsLAN() {
    return XPGConnectJNI.XPGWifiDevice_IsLAN(swigCPtr, this);
  }

  public boolean IsOnline() {
    return XPGConnectJNI.XPGWifiDevice_IsOnline(swigCPtr, this);
  }

  public boolean IsControl() {
    return XPGConnectJNI.XPGWifiDevice_IsControl(swigCPtr, this);
  }

  public boolean GetPasscodeFromDevice() {
    return XPGConnectJNI.XPGWifiDevice_GetPasscodeFromDevice(swigCPtr, this);
  }

  public boolean ConnectToLAN() {
    return XPGConnectJNI.XPGWifiDevice_ConnectToLAN(swigCPtr, this);
  }

  public boolean ConnectToMQTT() {
    return XPGConnectJNI.XPGWifiDevice_ConnectToMQTT(swigCPtr, this);
  }

  public boolean Connect() {
    return XPGConnectJNI.XPGWifiDevice_Connect(swigCPtr, this);
  }

  public boolean Disconnect() {
    return XPGConnectJNI.XPGWifiDevice_Disconnect(swigCPtr, this);
  }

  public void Login(String username, String password) {
    XPGConnectJNI.XPGWifiDevice_Login(swigCPtr, this, username, password);
  }

  public boolean IsBind(String username) {
    return XPGConnectJNI.XPGWifiDevice_IsBind(swigCPtr, this, username);
  }

  public boolean Bind(String username) {
    return XPGConnectJNI.XPGWifiDevice_Bind(swigCPtr, this, username);
  }

  public boolean UnBind(String username) {
    return XPGConnectJNI.XPGWifiDevice_UnBind(swigCPtr, this, username);
  }

  public void UnBindFromService(String username, String password) {
    XPGConnectJNI.XPGWifiDevice_UnBindFromService(swigCPtr, this, username, password);
  }

  public int write_bytes(byte[] data) {
    return XPGConnectJNI.XPGWifiDevice_write_bytes(swigCPtr, this, data);
  }

  public int write(String json) {
    return XPGConnectJNI.XPGWifiDevice_write(swigCPtr, this, json);
  }

  public String GetUI() {
    return XPGConnectJNI.XPGWifiDevice_GetUI(swigCPtr, this);
  }

  public String ForceUpdateUI() {
    return XPGConnectJNI.XPGWifiDevice_ForceUpdateUI(swigCPtr, this);
  }

  public boolean SetSwitcher(boolean bMaster) {
    return XPGConnectJNI.XPGWifiDevice_SetSwitcher(swigCPtr, this, bMaster);
  }

}
