/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public final class XPGWifiErrorCode {
  public final static XPGWifiErrorCode XPGWifiError_NONE = new XPGWifiErrorCode("XPGWifiError_NONE", XPGConnectJNI.XPGWifiError_NONE_get());
  public final static XPGWifiErrorCode XPGWifiError_GENERAL = new XPGWifiErrorCode("XPGWifiError_GENERAL", XPGConnectJNI.XPGWifiError_GENERAL_get());
  public final static XPGWifiErrorCode XPGWifiError_NOT_IMPLEMENTED = new XPGWifiErrorCode("XPGWifiError_NOT_IMPLEMENTED", XPGConnectJNI.XPGWifiError_NOT_IMPLEMENTED_get());
  public final static XPGWifiErrorCode XPGWifiError_DESCRIPTOR_FAIL = new XPGWifiErrorCode("XPGWifiError_DESCRIPTOR_FAIL", XPGConnectJNI.XPGWifiError_DESCRIPTOR_FAIL_get());
  public final static XPGWifiErrorCode XPGWifiError_PACKET_DATALEN = new XPGWifiErrorCode("XPGWifiError_PACKET_DATALEN", XPGConnectJNI.XPGWifiError_PACKET_DATALEN_get());
  public final static XPGWifiErrorCode XPGWifiError_CONNECTION_ID = new XPGWifiErrorCode("XPGWifiError_CONNECTION_ID", XPGConnectJNI.XPGWifiError_CONNECTION_ID_get());
  public final static XPGWifiErrorCode XPGWifiError_PATH = new XPGWifiErrorCode("XPGWifiError_PATH", XPGConnectJNI.XPGWifiError_PATH_get());
  public final static XPGWifiErrorCode XPGWifiError_CONNECTION_CLOSED = new XPGWifiErrorCode("XPGWifiError_CONNECTION_CLOSED", XPGConnectJNI.XPGWifiError_CONNECTION_CLOSED_get());
  public final static XPGWifiErrorCode XPGWifiError_PACKET_CHECKSUM = new XPGWifiErrorCode("XPGWifiError_PACKET_CHECKSUM", XPGConnectJNI.XPGWifiError_PACKET_CHECKSUM_get());
  public final static XPGWifiErrorCode XPGWifiError_LOGIN_FAIL = new XPGWifiErrorCode("XPGWifiError_LOGIN_FAIL", XPGConnectJNI.XPGWifiError_LOGIN_FAIL_get());
  public final static XPGWifiErrorCode XPGWifiError_DOMAIN_NAME = new XPGWifiErrorCode("XPGWifiError_DOMAIN_NAME", XPGConnectJNI.XPGWifiError_DOMAIN_NAME_get());
  public final static XPGWifiErrorCode XPGWifiError_MQTT_FAIL = new XPGWifiErrorCode("XPGWifiError_MQTT_FAIL", XPGConnectJNI.XPGWifiError_MQTT_FAIL_get());
  public final static XPGWifiErrorCode XPGWifiError_DISCOVERY_MISMATCH = new XPGWifiErrorCode("XPGWifiError_DISCOVERY_MISMATCH", XPGConnectJNI.XPGWifiError_DISCOVERY_MISMATCH_get());
  public final static XPGWifiErrorCode XPGWifiError_SET_SOCK_OPT = new XPGWifiErrorCode("XPGWifiError_SET_SOCK_OPT", XPGConnectJNI.XPGWifiError_SET_SOCK_OPT_get());
  public final static XPGWifiErrorCode XPGWifiError_THREAD_CREATE = new XPGWifiErrorCode("XPGWifiError_THREAD_CREATE", XPGConnectJNI.XPGWifiError_THREAD_CREATE_get());
  public final static XPGWifiErrorCode XPGWifiError_NULL_MAC = new XPGWifiErrorCode("XPGWifiError_NULL_MAC", XPGConnectJNI.XPGWifiError_NULL_MAC_get());
  public final static XPGWifiErrorCode XPGWifiError_CONNECTION_POOL_FULLED = new XPGWifiErrorCode("XPGWifiError_CONNECTION_POOL_FULLED", XPGConnectJNI.XPGWifiError_CONNECTION_POOL_FULLED_get());
  public final static XPGWifiErrorCode XPGWifiError_NULL_CLIENT_ID = new XPGWifiErrorCode("XPGWifiError_NULL_CLIENT_ID", XPGConnectJNI.XPGWifiError_NULL_CLIENT_ID_get());
  public final static XPGWifiErrorCode XPGWifiError_CONNECTION_ERROR = new XPGWifiErrorCode("XPGWifiError_CONNECTION_ERROR", XPGConnectJNI.XPGWifiError_CONNECTION_ERROR_get());
  public final static XPGWifiErrorCode XPGWifiError_INVALID_PARAM = new XPGWifiErrorCode("XPGWifiError_INVALID_PARAM", XPGConnectJNI.XPGWifiError_INVALID_PARAM_get());
  public final static XPGWifiErrorCode XPGWifiError_CONNECT_TIMEOUT = new XPGWifiErrorCode("XPGWifiError_CONNECT_TIMEOUT", XPGConnectJNI.XPGWifiError_CONNECT_TIMEOUT_get());
  public final static XPGWifiErrorCode XPGWifiError_INVALID_VERSION = new XPGWifiErrorCode("XPGWifiError_INVALID_VERSION", XPGConnectJNI.XPGWifiError_INVALID_VERSION_get());
  public final static XPGWifiErrorCode XPGWifiError_INSUFFIENT_MEM = new XPGWifiErrorCode("XPGWifiError_INSUFFIENT_MEM", XPGConnectJNI.XPGWifiError_INSUFFIENT_MEM_get());
  public final static XPGWifiErrorCode XPGWifiError_THREAD_BUSY = new XPGWifiErrorCode("XPGWifiError_THREAD_BUSY", XPGConnectJNI.XPGWifiError_THREAD_BUSY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XPGWifiErrorCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XPGWifiErrorCode.class + " with value " + swigValue);
  }

  private XPGWifiErrorCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XPGWifiErrorCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XPGWifiErrorCode(String swigName, XPGWifiErrorCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XPGWifiErrorCode[] swigValues = { XPGWifiError_NONE, XPGWifiError_GENERAL, XPGWifiError_NOT_IMPLEMENTED, XPGWifiError_DESCRIPTOR_FAIL, XPGWifiError_PACKET_DATALEN, XPGWifiError_CONNECTION_ID, XPGWifiError_PATH, XPGWifiError_CONNECTION_CLOSED, XPGWifiError_PACKET_CHECKSUM, XPGWifiError_LOGIN_FAIL, XPGWifiError_DOMAIN_NAME, XPGWifiError_MQTT_FAIL, XPGWifiError_DISCOVERY_MISMATCH, XPGWifiError_SET_SOCK_OPT, XPGWifiError_THREAD_CREATE, XPGWifiError_NULL_MAC, XPGWifiError_CONNECTION_POOL_FULLED, XPGWifiError_NULL_CLIENT_ID, XPGWifiError_CONNECTION_ERROR, XPGWifiError_INVALID_PARAM, XPGWifiError_CONNECT_TIMEOUT, XPGWifiError_INVALID_VERSION, XPGWifiError_INSUFFIENT_MEM, XPGWifiError_THREAD_BUSY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

