/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiDatabase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiDatabase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiDatabase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiDatabase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean SetStorePath(String szPath) {
    return XPGConnectJNI.XPGWifiDatabase_SetStorePath(szPath);
  }

  public static void ClearAll() {
    XPGConnectJNI.XPGWifiDatabase_ClearAll();
  }

  public XPGWifiDatabase() {
    this(XPGConnectJNI.new_XPGWifiDatabase(), true);
  }

}
