/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiSSID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiSSID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiSSID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiSSID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSsid(String value) {
    XPGConnectJNI.XPGWifiSSID_ssid_set(swigCPtr, this, value);
  }

  public String getSsid() {
    return XPGConnectJNI.XPGWifiSSID_ssid_get(swigCPtr, this);
  }

  public void setRssi(short value) {
    XPGConnectJNI.XPGWifiSSID_rssi_set(swigCPtr, this, value);
  }

  public short getRssi() {
    return XPGConnectJNI.XPGWifiSSID_rssi_get(swigCPtr, this);
  }

  public XPGWifiSSID() {
    this(XPGConnectJNI.new_XPGWifiSSID(), true);
  }

}
