/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiSDKListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiSDKListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiSDKListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiSDKListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XPGConnectJNI.XPGWifiSDKListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XPGConnectJNI.XPGWifiSDKListener_change_ownership(this, swigCPtr, true);
  }

  public void onGetSSIDList(XPGWifiSSIDList list, int result) {
    XPGConnectJNI.XPGWifiSDKListener_onGetSSIDList(swigCPtr, this, XPGWifiSSIDList.getCPtr(list), list, result);
  }

  public void onSetAirLink(XPGWifiDevice device) {
    XPGConnectJNI.XPGWifiSDKListener_onSetAirLink(swigCPtr, this, XPGWifiDevice.getCPtr(device), device);
  }

  public void onDiscovered(int result, XPGWifiDeviceList devices) {
    XPGConnectJNI.XPGWifiSDKListener_onDiscovered(swigCPtr, this, result, XPGWifiDeviceList.getCPtr(devices), devices);
  }

  public void onRegisterUser(int result) {
    XPGConnectJNI.XPGWifiSDKListener_onRegisterUser(swigCPtr, this, result);
  }

  public void onPrepareBindListFromLocal(int result) {
    XPGConnectJNI.XPGWifiSDKListener_onPrepareBindListFromLocal(swigCPtr, this, result);
  }

  public void onUpdatedBindListFromServer(int result) {
    XPGConnectJNI.XPGWifiSDKListener_onUpdatedBindListFromServer(swigCPtr, this, result);
  }

  public long onCalculateCRC(byte[] data) {
    return XPGConnectJNI.XPGWifiSDKListener_onCalculateCRC(swigCPtr, this, data);
  }

  public void onUpdateProduct(int result) {
    XPGConnectJNI.XPGWifiSDKListener_onUpdateProduct(swigCPtr, this, result);
  }

  public XPGWifiSDKListener() {
    this(XPGConnectJNI.new_XPGWifiSDKListener(), true);
    XPGConnectJNI.XPGWifiSDKListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
