/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiBinding {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiBinding(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiBinding obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiBinding(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzMac(String value) {
    XPGConnectJNI.XPGWifiBinding_szMac_set(swigCPtr, this, value);
  }

  public String getSzMac() {
    return XPGConnectJNI.XPGWifiBinding_szMac_get(swigCPtr, this);
  }

  public void setSzDid(String value) {
    XPGConnectJNI.XPGWifiBinding_szDid_set(swigCPtr, this, value);
  }

  public String getSzDid() {
    return XPGConnectJNI.XPGWifiBinding_szDid_get(swigCPtr, this);
  }

  public void setSzPasscode(String value) {
    XPGConnectJNI.XPGWifiBinding_szPasscode_set(swigCPtr, this, value);
  }

  public String getSzPasscode() {
    return XPGConnectJNI.XPGWifiBinding_szPasscode_get(swigCPtr, this);
  }

  public XPGWifiBinding() {
    this(XPGConnectJNI.new_XPGWifiBinding(), true);
  }

}
