/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiSDK {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiSDK(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiSDK obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setListener(XPGWifiSDKListener value) {
    XPGConnectJNI.XPGWifiSDK_listener_set(swigCPtr, this, XPGWifiSDKListener.getCPtr(value), value);
  }

  public XPGWifiSDKListener getListener() {
    long cPtr = XPGConnectJNI.XPGWifiSDK_listener_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XPGWifiSDKListener(cPtr, false);
  }

  public static XPGWifiSDK sharedInstance() {
    long cPtr = XPGConnectJNI.XPGWifiSDK_sharedInstance();
    return (cPtr == 0) ? null : new XPGWifiSDK(cPtr, false);
  }

  public static void SetLogLevel(XPGWifiLogLevel level) {
    XPGConnectJNI.XPGWifiSDK_SetLogLevel(level.swigValue());
  }

  public static void SetLogFile(String lpFileName) {
    XPGConnectJNI.XPGWifiSDK_SetLogFile(lpFileName);
  }

  public static void SetPrintDataLevel(boolean isDebug) {
    XPGConnectJNI.XPGWifiSDK_SetPrintDataLevel(isDebug);
  }

  public boolean SetSSID(String ssid, String key) {
    return XPGConnectJNI.XPGWifiSDK_SetSSID(swigCPtr, this, ssid, key);
  }

  public void GetSSIDList() {
    XPGConnectJNI.XPGWifiSDK_GetSSIDList(swigCPtr, this);
  }

  public boolean SetAirLink(String ssid, String key) {
    return XPGConnectJNI.XPGWifiSDK_SetAirLink(swigCPtr, this, ssid, key);
  }

  public boolean DiscoverDevices() {
    return XPGConnectJNI.XPGWifiSDK_DiscoverDevices(swigCPtr, this);
  }

  public void PrepareBindListFromLocal(String szUserName) {
    XPGConnectJNI.XPGWifiSDK_PrepareBindListFromLocal(swigCPtr, this, szUserName);
  }

  public void ClearPreparedBindList() {
    XPGConnectJNI.XPGWifiSDK_ClearPreparedBindList(swigCPtr, this);
  }

  public void UpdateLocalBindListFromServer(String szUserName, String szPassword, float timeout) {
    XPGConnectJNI.XPGWifiSDK_UpdateLocalBindListFromServer(swigCPtr, this, szUserName, szPassword, timeout);
  }

  public void RegisterUserFromServer(String szUserName, String szPassword) {
    XPGConnectJNI.XPGWifiSDK_RegisterUserFromServer(swigCPtr, this, szUserName, szPassword);
  }

}
