/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiDeviceList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiDeviceList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiDeviceList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiDeviceList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long GetCount() {
    return XPGConnectJNI.XPGWifiDeviceList_GetCount(swigCPtr, this);
  }

  public XPGWifiDevice GetItem(int index) {
    long cPtr = XPGConnectJNI.XPGWifiDeviceList_GetItem(swigCPtr, this, index);
    return (cPtr == 0) ? null : new XPGWifiDevice(cPtr, false);
  }

  public XPGWifiDeviceList() {
    this(XPGConnectJNI.new_XPGWifiDeviceList(), true);
  }

}
