/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiDeviceListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiDeviceListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiDeviceListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiDeviceListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XPGConnectJNI.XPGWifiDeviceListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XPGConnectJNI.XPGWifiDeviceListener_change_ownership(this, swigCPtr, true);
  }

  public void onConnected() {
    XPGConnectJNI.XPGWifiDeviceListener_onConnected(swigCPtr, this);
  }

  public void onConnectFailed() {
    XPGConnectJNI.XPGWifiDeviceListener_onConnectFailed(swigCPtr, this);
  }

  public void onDisconnected() {
    XPGConnectJNI.XPGWifiDeviceListener_onDisconnected(swigCPtr, this);
  }

  public void onGetPasscode(int result) {
    XPGConnectJNI.XPGWifiDeviceListener_onGetPasscode(swigCPtr, this, result);
  }

  public void onLogin(int result) {
    XPGConnectJNI.XPGWifiDeviceListener_onLogin(swigCPtr, this, result);
  }

  public void onLoginMQTT(int result) {
    XPGConnectJNI.XPGWifiDeviceListener_onLoginMQTT(swigCPtr, this, result);
  }

  public boolean onReceiveData(String data) {
    return XPGConnectJNI.XPGWifiDeviceListener_onReceiveData(swigCPtr, this, data);
  }

  public void onUnbindFromServices(int result) {
    XPGConnectJNI.XPGWifiDeviceListener_onUnbindFromServices(swigCPtr, this, result);
  }

  public void onDeviceOnline(boolean isOnline) {
    XPGConnectJNI.XPGWifiDeviceListener_onDeviceOnline(swigCPtr, this, isOnline);
  }

  public void onSetSwitcher(int result) {
    XPGConnectJNI.XPGWifiDeviceListener_onSetSwitcher(swigCPtr, this, result);
  }

  public void onDeviceLog(short nLevel, String tag, String source, String content) {
    XPGConnectJNI.XPGWifiDeviceListener_onDeviceLog(swigCPtr, this, nLevel, tag, source, content);
  }

  public XPGWifiDeviceListener() {
    this(XPGConnectJNI.new_XPGWifiDeviceListener(), true);
    XPGConnectJNI.XPGWifiDeviceListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
