/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public final class XPGWifiLoginErrorCode {
  public final static XPGWifiLoginErrorCode XPGWifiLoginError_CONTROL_ENABLED = new XPGWifiLoginErrorCode("XPGWifiLoginError_CONTROL_ENABLED", XPGConnectJNI.XPGWifiLoginError_CONTROL_ENABLED_get());
  public final static XPGWifiLoginErrorCode XPGWifiLoginError_LOGINED = new XPGWifiLoginErrorCode("XPGWifiLoginError_LOGINED");
  public final static XPGWifiLoginErrorCode XPGWifiLoginError_FAILED = new XPGWifiLoginErrorCode("XPGWifiLoginError_FAILED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XPGWifiLoginErrorCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XPGWifiLoginErrorCode.class + " with value " + swigValue);
  }

  private XPGWifiLoginErrorCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XPGWifiLoginErrorCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XPGWifiLoginErrorCode(String swigName, XPGWifiLoginErrorCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XPGWifiLoginErrorCode[] swigValues = { XPGWifiLoginError_CONTROL_ENABLED, XPGWifiLoginError_LOGINED, XPGWifiLoginError_FAILED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

