/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.xtremeprog.xpgconnect;

public class XPGWifiConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XPGWifiConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XPGWifiConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XPGConnectJNI.delete_XPGWifiConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XPGWifiConfig() {
    this(XPGConnectJNI.new_XPGWifiConfig(), true);
  }

  public static XPGWifiConfig sharedInstance() {
    long cPtr = XPGConnectJNI.XPGWifiConfig_sharedInstance();
    return (cPtr == 0) ? null : new XPGWifiConfig(cPtr, false);
  }

  public boolean SetProductPath(String path) {
    return XPGConnectJNI.XPGWifiConfig_SetProductPath(swigCPtr, this, path);
  }

  public boolean AddProduct(String str, String productKey) {
    return XPGConnectJNI.XPGWifiConfig_AddProduct(swigCPtr, this, str, productKey);
  }

  public void DownloadProduct(String productKey) {
    XPGConnectJNI.XPGWifiConfig_DownloadProduct(swigCPtr, this, productKey);
  }

  public void SetDebug(boolean isDebug) {
    XPGConnectJNI.XPGWifiConfig_SetDebug(swigCPtr, this, isDebug);
  }

  public void SetSwitchService(boolean isDebugService) {
    XPGConnectJNI.XPGWifiConfig_SetSwitchService(swigCPtr, this, isDebugService);
  }

  public void EnableProductFilter(boolean bEnable) {
    XPGConnectJNI.XPGWifiConfig_EnableProductFilter(swigCPtr, this, bEnable);
  }

  public void RegisterProductKey(String product) {
    XPGConnectJNI.XPGWifiConfig_RegisterProductKey(swigCPtr, this, product);
  }

  public void RegisterSSID(String ssid) {
    XPGConnectJNI.XPGWifiConfig_RegisterSSID(swigCPtr, this, ssid);
  }

  public void ClearProductKeys() {
    XPGConnectJNI.XPGWifiConfig_ClearProductKeys(swigCPtr, this);
  }

  public void ClearSSIDs() {
    XPGConnectJNI.XPGWifiConfig_ClearSSIDs(swigCPtr, this);
  }

  public int GetTCPPort() {
    return XPGConnectJNI.XPGWifiConfig_GetTCPPort(swigCPtr, this);
  }

  public int GetUDPPort() {
    return XPGConnectJNI.XPGWifiConfig_GetUDPPort(swigCPtr, this);
  }

  public String GetMQTTCommunication() {
    return XPGConnectJNI.XPGWifiConfig_GetMQTTCommunication(swigCPtr, this);
  }

  public int GetMQTTCommunicationPort() {
    return XPGConnectJNI.XPGWifiConfig_GetMQTTCommunicationPort(swigCPtr, this);
  }

  public String GetMQTTUpdate() {
    return XPGConnectJNI.XPGWifiConfig_GetMQTTUpdate(swigCPtr, this);
  }

  public int GetMQTTUpdatePort() {
    return XPGConnectJNI.XPGWifiConfig_GetMQTTUpdatePort(swigCPtr, this);
  }

  public int GetAirlinkPort() {
    return XPGConnectJNI.XPGWifiConfig_GetAirlinkPort(swigCPtr, this);
  }

  public int GetSoftAPCount() {
    return XPGConnectJNI.XPGWifiConfig_GetSoftAPCount(swigCPtr, this);
  }

  public String GetSoftAPSSID(int nIndex) {
    return XPGConnectJNI.XPGWifiConfig_GetSoftAPSSID(swigCPtr, this, nIndex);
  }

}
